// Shared portable generator, copied byte-identically into the three independent products.
import fs from 'node:fs';
import Ajv from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';

export function buildValidators(directory, schemas, exports, configure) {
  const ajv = new Ajv({ allErrors: true, strict: true, strictRequired: false, code: { source: true, esm: true, lines: true } });
  configure?.(ajv);
  for (const schema of schemas) ajv.addSchema(schema);
  let source = standaloneCode(ajv, exports);
  // Ajv's ESM output still emits CJS imports for runtime helpers. Convert the
  // reviewed dependencies explicitly; fail on a new helper instead of shipping
  // browser-incompatible require() or weakening the application's CSP.
  const runtimeImports = {
    'ajv/dist/runtime/equal': 'ajv/dist/runtime/equal.js',
    'ajv/dist/runtime/ucs2length': 'ajv/dist/runtime/ucs2length.js',
    'ajv-formats/dist/formats': 'ajv-formats/dist/formats.js',
  };
  const dependencies = [...new Set([...source.matchAll(/require\("([^"]+)"\)/g)].map(match => match[1]))].sort();
  const imports = dependencies.map((dependency, i) => {
    if (!runtimeImports[dependency]) throw new Error(`Unreviewed standalone runtime helper: ${dependency}`);
    if (dependency.startsWith('ajv/dist/runtime/')) {
      source = source.replaceAll(`require("${dependency}").default`, `runtime${i}`);
      // Node exposes these CJS helpers as {default: fn}; bundlers may expose fn.
      return `import module${i} from '${runtimeImports[dependency]}';\nconst runtime${i} = module${i}.default ?? module${i};`;
    }
    // ajv-formats marks its CJS exports __esModule without a default export.
    // Named access is portable across Node, Vite dev and production bundlers.
    source = source.replaceAll(`require("${dependency}").fullFormats`, `runtime${i}`);
    return `import { fullFormats as runtime${i} } from '${runtimeImports[dependency]}';`;
  });
  if (/\brequire\s*\(|new Function\s*\(/.test(source)) throw new Error('Standalone validators must not require runtime code generation or CJS require');
  source = ('// Generated by scripts/build-validators.js; do not edit.\n' + imports.join('\n') + '\n' + source).trimEnd() + '\n';
  const destination = new URL('validators.js', directory);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== source) throw new Error('Generated validators are stale; run node scripts/build-validators.js');
  } else fs.writeFileSync(destination, source);
}
