// Generated by scripts/build-validators.js; do not edit.
import module0 from 'ajv/dist/runtime/ucs2length.js';
const runtime0 = module0.default ?? module0;
"use strict";
export const validateDocumentShape = validate20;
const schema31 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://pictos.net/schemas/pictogram-composition-0.1.0.schema.json","title":"Pictogram composition accepted artifact 0.1.0","type":"object","additionalProperties":false,"required":["elements","prompt"],"properties":{"elements":{"type":"array","minItems":1,"items":{"type":"object","additionalProperties":false,"required":["id","concept","children"],"properties":{"id":{"enum":["pictograma","pictogram"]},"concept":{"const":"Root"},"children":{"type":"array","minItems":1,"items":{"$ref":"#/$defs/Element"}}}},"description":"Semantic children only. Root is constructed locally, never by the provider.","maxItems":1},"prompt":{"type":"string","pattern":"\\S","description":"Spatial topology. Reference every semantic element ID in single quotes. No visual style."}},"$defs":{"Element":{"type":"object","additionalProperties":false,"required":["id","concept"],"properties":{"id":{"type":"string","pattern":"^[^\\s']+$","minLength":1,"description":"Unique semantic identifier. A noun in the utterance language; snake_case for compounds."},"concept":{"type":"string","enum":["Agent","Action","Object","Context","Element"]},"children":{"type":"array","items":{"$ref":"#/$defs/Element"}}}}}};
const schema32 = {"type":"object","additionalProperties":false,"required":["id","concept"],"properties":{"id":{"type":"string","pattern":"^[^\\s']+$","minLength":1,"description":"Unique semantic identifier. A noun in the utterance language; snake_case for compounds."},"concept":{"type":"string","enum":["Agent","Action","Object","Context","Element"]},"children":{"type":"array","items":{"$ref":"#/$defs/Element"}}}};
const func1 = runtime0;
const pattern4 = new RegExp("^[^\\s']+$", "u");
const wrapper0 = {validate: validate21};

function validate21(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
let vErrors = null;
let errors = 0;
const evaluated0 = validate21.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.id === undefined){
const err0 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "id"},message:"must have required property '"+"id"+"'"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.concept === undefined){
const err1 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "concept"},message:"must have required property '"+"concept"+"'"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
for(const key0 in data){
if(!(((key0 === "id") || (key0 === "concept")) || (key0 === "children"))){
const err2 = {instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
}
if(data.id !== undefined){
let data0 = data.id;
if(typeof data0 === "string"){
if(func1(data0) < 1){
const err3 = {instancePath:instancePath+"/id",schemaPath:"#/properties/id/minLength",keyword:"minLength",params:{limit: 1},message:"must NOT have fewer than 1 characters"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
if(!pattern4.test(data0)){
const err4 = {instancePath:instancePath+"/id",schemaPath:"#/properties/id/pattern",keyword:"pattern",params:{pattern: "^[^\\s']+$"},message:"must match pattern \""+"^[^\\s']+$"+"\""};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
}
else {
const err5 = {instancePath:instancePath+"/id",schemaPath:"#/properties/id/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
}
if(data.concept !== undefined){
let data1 = data.concept;
if(typeof data1 !== "string"){
const err6 = {instancePath:instancePath+"/concept",schemaPath:"#/properties/concept/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
if(!(((((data1 === "Agent") || (data1 === "Action")) || (data1 === "Object")) || (data1 === "Context")) || (data1 === "Element"))){
const err7 = {instancePath:instancePath+"/concept",schemaPath:"#/properties/concept/enum",keyword:"enum",params:{allowedValues: schema32.properties.concept.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
}
if(data.children !== undefined){
let data2 = data.children;
if(Array.isArray(data2)){
const len0 = data2.length;
for(let i0=0; i0<len0; i0++){
if(!(wrapper0.validate(data2[i0], {instancePath:instancePath+"/children/" + i0,parentData:data2,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? wrapper0.validate.errors : vErrors.concat(wrapper0.validate.errors);
errors = vErrors.length;
}
}
}
else {
const err8 = {instancePath:instancePath+"/children",schemaPath:"#/properties/children/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err8];
}
else {
vErrors.push(err8);
}
errors++;
}
}
}
else {
const err9 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err9];
}
else {
vErrors.push(err9);
}
errors++;
}
validate21.errors = vErrors;
return errors === 0;
}
validate21.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

const pattern5 = new RegExp("\\S", "u");

function validate20(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://pictos.net/schemas/pictogram-composition-0.1.0.schema.json" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate20.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.elements === undefined){
const err0 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "elements"},message:"must have required property '"+"elements"+"'"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.prompt === undefined){
const err1 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "prompt"},message:"must have required property '"+"prompt"+"'"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
for(const key0 in data){
if(!((key0 === "elements") || (key0 === "prompt"))){
const err2 = {instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
}
if(data.elements !== undefined){
let data0 = data.elements;
if(Array.isArray(data0)){
if(data0.length > 1){
const err3 = {instancePath:instancePath+"/elements",schemaPath:"#/properties/elements/maxItems",keyword:"maxItems",params:{limit: 1},message:"must NOT have more than 1 items"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
if(data0.length < 1){
const err4 = {instancePath:instancePath+"/elements",schemaPath:"#/properties/elements/minItems",keyword:"minItems",params:{limit: 1},message:"must NOT have fewer than 1 items"};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
const len0 = data0.length;
for(let i0=0; i0<len0; i0++){
let data1 = data0[i0];
if(data1 && typeof data1 == "object" && !Array.isArray(data1)){
if(data1.id === undefined){
const err5 = {instancePath:instancePath+"/elements/" + i0,schemaPath:"#/properties/elements/items/required",keyword:"required",params:{missingProperty: "id"},message:"must have required property '"+"id"+"'"};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
if(data1.concept === undefined){
const err6 = {instancePath:instancePath+"/elements/" + i0,schemaPath:"#/properties/elements/items/required",keyword:"required",params:{missingProperty: "concept"},message:"must have required property '"+"concept"+"'"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
if(data1.children === undefined){
const err7 = {instancePath:instancePath+"/elements/" + i0,schemaPath:"#/properties/elements/items/required",keyword:"required",params:{missingProperty: "children"},message:"must have required property '"+"children"+"'"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
for(const key1 in data1){
if(!(((key1 === "id") || (key1 === "concept")) || (key1 === "children"))){
const err8 = {instancePath:instancePath+"/elements/" + i0,schemaPath:"#/properties/elements/items/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key1},message:"must NOT have additional properties"};
if(vErrors === null){
vErrors = [err8];
}
else {
vErrors.push(err8);
}
errors++;
}
}
if(data1.id !== undefined){
let data2 = data1.id;
if(!((data2 === "pictograma") || (data2 === "pictogram"))){
const err9 = {instancePath:instancePath+"/elements/" + i0+"/id",schemaPath:"#/properties/elements/items/properties/id/enum",keyword:"enum",params:{allowedValues: schema31.properties.elements.items.properties.id.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err9];
}
else {
vErrors.push(err9);
}
errors++;
}
}
if(data1.concept !== undefined){
if("Root" !== data1.concept){
const err10 = {instancePath:instancePath+"/elements/" + i0+"/concept",schemaPath:"#/properties/elements/items/properties/concept/const",keyword:"const",params:{allowedValue: "Root"},message:"must be equal to constant"};
if(vErrors === null){
vErrors = [err10];
}
else {
vErrors.push(err10);
}
errors++;
}
}
if(data1.children !== undefined){
let data4 = data1.children;
if(Array.isArray(data4)){
if(data4.length < 1){
const err11 = {instancePath:instancePath+"/elements/" + i0+"/children",schemaPath:"#/properties/elements/items/properties/children/minItems",keyword:"minItems",params:{limit: 1},message:"must NOT have fewer than 1 items"};
if(vErrors === null){
vErrors = [err11];
}
else {
vErrors.push(err11);
}
errors++;
}
const len1 = data4.length;
for(let i1=0; i1<len1; i1++){
if(!(validate21(data4[i1], {instancePath:instancePath+"/elements/" + i0+"/children/" + i1,parentData:data4,parentDataProperty:i1,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate21.errors : vErrors.concat(validate21.errors);
errors = vErrors.length;
}
}
}
else {
const err12 = {instancePath:instancePath+"/elements/" + i0+"/children",schemaPath:"#/properties/elements/items/properties/children/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err12];
}
else {
vErrors.push(err12);
}
errors++;
}
}
}
else {
const err13 = {instancePath:instancePath+"/elements/" + i0,schemaPath:"#/properties/elements/items/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err13];
}
else {
vErrors.push(err13);
}
errors++;
}
}
}
else {
const err14 = {instancePath:instancePath+"/elements",schemaPath:"#/properties/elements/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err14];
}
else {
vErrors.push(err14);
}
errors++;
}
}
if(data.prompt !== undefined){
let data6 = data.prompt;
if(typeof data6 === "string"){
if(!pattern5.test(data6)){
const err15 = {instancePath:instancePath+"/prompt",schemaPath:"#/properties/prompt/pattern",keyword:"pattern",params:{pattern: "\\S"},message:"must match pattern \""+"\\S"+"\""};
if(vErrors === null){
vErrors = [err15];
}
else {
vErrors.push(err15);
}
errors++;
}
}
else {
const err16 = {instancePath:instancePath+"/prompt",schemaPath:"#/properties/prompt/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err16];
}
else {
vErrors.push(err16);
}
errors++;
}
}
}
else {
const err17 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err17];
}
else {
vErrors.push(err17);
}
errors++;
}
validate20.errors = vErrors;
return errors === 0;
}
validate20.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const validateProviderShape = validate23;
const schema33 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://pictos.net/schemas/pictogram-composition-provider-0.1.0.schema.json","title":"Pictogram composition provider output 0.1.0","type":"object","additionalProperties":false,"required":["elements","prompt"],"properties":{"elements":{"type":"array","minItems":1,"items":{"$ref":"#/$defs/Element"},"description":"Semantic children only. Root is constructed locally, never by the provider."},"prompt":{"type":"string","pattern":"\\S","description":"Spatial topology. Reference every semantic element ID in single quotes. No visual style."}},"$defs":{"Element":{"type":"object","additionalProperties":false,"required":["id","concept"],"properties":{"id":{"type":"string","pattern":"^[^\\s']+$","minLength":1,"description":"Unique semantic identifier. A noun in the utterance language; snake_case for compounds."},"concept":{"type":"string","enum":["Agent","Action","Object","Context","Element"]},"children":{"type":"array","items":{"$ref":"#/$defs/Element"}}}}}};
const schema34 = {"type":"object","additionalProperties":false,"required":["id","concept"],"properties":{"id":{"type":"string","pattern":"^[^\\s']+$","minLength":1,"description":"Unique semantic identifier. A noun in the utterance language; snake_case for compounds."},"concept":{"type":"string","enum":["Agent","Action","Object","Context","Element"]},"children":{"type":"array","items":{"$ref":"#/$defs/Element"}}}};
const wrapper1 = {validate: validate24};

function validate24(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
let vErrors = null;
let errors = 0;
const evaluated0 = validate24.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.id === undefined){
const err0 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "id"},message:"must have required property '"+"id"+"'"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.concept === undefined){
const err1 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "concept"},message:"must have required property '"+"concept"+"'"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
for(const key0 in data){
if(!(((key0 === "id") || (key0 === "concept")) || (key0 === "children"))){
const err2 = {instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
}
if(data.id !== undefined){
let data0 = data.id;
if(typeof data0 === "string"){
if(func1(data0) < 1){
const err3 = {instancePath:instancePath+"/id",schemaPath:"#/properties/id/minLength",keyword:"minLength",params:{limit: 1},message:"must NOT have fewer than 1 characters"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
if(!pattern4.test(data0)){
const err4 = {instancePath:instancePath+"/id",schemaPath:"#/properties/id/pattern",keyword:"pattern",params:{pattern: "^[^\\s']+$"},message:"must match pattern \""+"^[^\\s']+$"+"\""};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
}
else {
const err5 = {instancePath:instancePath+"/id",schemaPath:"#/properties/id/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
}
if(data.concept !== undefined){
let data1 = data.concept;
if(typeof data1 !== "string"){
const err6 = {instancePath:instancePath+"/concept",schemaPath:"#/properties/concept/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
if(!(((((data1 === "Agent") || (data1 === "Action")) || (data1 === "Object")) || (data1 === "Context")) || (data1 === "Element"))){
const err7 = {instancePath:instancePath+"/concept",schemaPath:"#/properties/concept/enum",keyword:"enum",params:{allowedValues: schema34.properties.concept.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
}
if(data.children !== undefined){
let data2 = data.children;
if(Array.isArray(data2)){
const len0 = data2.length;
for(let i0=0; i0<len0; i0++){
if(!(wrapper1.validate(data2[i0], {instancePath:instancePath+"/children/" + i0,parentData:data2,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? wrapper1.validate.errors : vErrors.concat(wrapper1.validate.errors);
errors = vErrors.length;
}
}
}
else {
const err8 = {instancePath:instancePath+"/children",schemaPath:"#/properties/children/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err8];
}
else {
vErrors.push(err8);
}
errors++;
}
}
}
else {
const err9 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err9];
}
else {
vErrors.push(err9);
}
errors++;
}
validate24.errors = vErrors;
return errors === 0;
}
validate24.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};


function validate23(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://pictos.net/schemas/pictogram-composition-provider-0.1.0.schema.json" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate23.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.elements === undefined){
const err0 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "elements"},message:"must have required property '"+"elements"+"'"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.prompt === undefined){
const err1 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "prompt"},message:"must have required property '"+"prompt"+"'"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
for(const key0 in data){
if(!((key0 === "elements") || (key0 === "prompt"))){
const err2 = {instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
}
if(data.elements !== undefined){
let data0 = data.elements;
if(Array.isArray(data0)){
if(data0.length < 1){
const err3 = {instancePath:instancePath+"/elements",schemaPath:"#/properties/elements/minItems",keyword:"minItems",params:{limit: 1},message:"must NOT have fewer than 1 items"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
const len0 = data0.length;
for(let i0=0; i0<len0; i0++){
if(!(validate24(data0[i0], {instancePath:instancePath+"/elements/" + i0,parentData:data0,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate24.errors : vErrors.concat(validate24.errors);
errors = vErrors.length;
}
}
}
else {
const err4 = {instancePath:instancePath+"/elements",schemaPath:"#/properties/elements/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
}
if(data.prompt !== undefined){
let data2 = data.prompt;
if(typeof data2 === "string"){
if(!pattern5.test(data2)){
const err5 = {instancePath:instancePath+"/prompt",schemaPath:"#/properties/prompt/pattern",keyword:"pattern",params:{pattern: "\\S"},message:"must match pattern \""+"\\S"+"\""};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
}
else {
const err6 = {instancePath:instancePath+"/prompt",schemaPath:"#/properties/prompt/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
}
}
else {
const err7 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
validate23.errors = vErrors;
return errors === 0;
}
validate23.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const validateElementShape = validate26;
const schema35 = {"type":"array","minItems":1,"items":{"type":"object","additionalProperties":false,"required":["id","concept","children"],"properties":{"id":{"enum":["pictograma","pictogram"]},"concept":{"const":"Root"},"children":{"type":"array","minItems":1,"items":{"$ref":"#/$defs/Element"}}}},"description":"Semantic children only. Root is constructed locally, never by the provider.","maxItems":1};

function validate26(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
let vErrors = null;
let errors = 0;
const evaluated0 = validate26.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(Array.isArray(data)){
if(data.length > 1){
const err0 = {instancePath,schemaPath:"#/maxItems",keyword:"maxItems",params:{limit: 1},message:"must NOT have more than 1 items"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.length < 1){
const err1 = {instancePath,schemaPath:"#/minItems",keyword:"minItems",params:{limit: 1},message:"must NOT have fewer than 1 items"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
const len0 = data.length;
for(let i0=0; i0<len0; i0++){
let data0 = data[i0];
if(data0 && typeof data0 == "object" && !Array.isArray(data0)){
if(data0.id === undefined){
const err2 = {instancePath:instancePath+"/" + i0,schemaPath:"#/items/required",keyword:"required",params:{missingProperty: "id"},message:"must have required property '"+"id"+"'"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
if(data0.concept === undefined){
const err3 = {instancePath:instancePath+"/" + i0,schemaPath:"#/items/required",keyword:"required",params:{missingProperty: "concept"},message:"must have required property '"+"concept"+"'"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
if(data0.children === undefined){
const err4 = {instancePath:instancePath+"/" + i0,schemaPath:"#/items/required",keyword:"required",params:{missingProperty: "children"},message:"must have required property '"+"children"+"'"};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
for(const key0 in data0){
if(!(((key0 === "id") || (key0 === "concept")) || (key0 === "children"))){
const err5 = {instancePath:instancePath+"/" + i0,schemaPath:"#/items/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
}
if(data0.id !== undefined){
let data1 = data0.id;
if(!((data1 === "pictograma") || (data1 === "pictogram"))){
const err6 = {instancePath:instancePath+"/" + i0+"/id",schemaPath:"#/items/properties/id/enum",keyword:"enum",params:{allowedValues: schema35.items.properties.id.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
}
if(data0.concept !== undefined){
if("Root" !== data0.concept){
const err7 = {instancePath:instancePath+"/" + i0+"/concept",schemaPath:"#/items/properties/concept/const",keyword:"const",params:{allowedValue: "Root"},message:"must be equal to constant"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
}
if(data0.children !== undefined){
let data3 = data0.children;
if(Array.isArray(data3)){
if(data3.length < 1){
const err8 = {instancePath:instancePath+"/" + i0+"/children",schemaPath:"#/items/properties/children/minItems",keyword:"minItems",params:{limit: 1},message:"must NOT have fewer than 1 items"};
if(vErrors === null){
vErrors = [err8];
}
else {
vErrors.push(err8);
}
errors++;
}
const len1 = data3.length;
for(let i1=0; i1<len1; i1++){
if(!(validate21(data3[i1], {instancePath:instancePath+"/" + i0+"/children/" + i1,parentData:data3,parentDataProperty:i1,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate21.errors : vErrors.concat(validate21.errors);
errors = vErrors.length;
}
}
}
else {
const err9 = {instancePath:instancePath+"/" + i0+"/children",schemaPath:"#/items/properties/children/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err9];
}
else {
vErrors.push(err9);
}
errors++;
}
}
}
else {
const err10 = {instancePath:instancePath+"/" + i0,schemaPath:"#/items/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err10];
}
else {
vErrors.push(err10);
}
errors++;
}
}
}
else {
const err11 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "array"},message:"must be array"};
if(vErrors === null){
vErrors = [err11];
}
else {
vErrors.push(err11);
}
errors++;
}
validate26.errors = vErrors;
return errors === 0;
}
validate26.evaluated = {"items":true,"dynamicProps":false,"dynamicItems":false};
